-- -------------------------------------------------------
-- Truncate Table
-- ------------------------------------------------------

TRUNCATE TABLE product_category
TRUNCATE TABLE product


-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------

INSERT INTO product_category(category_name) VALUES ('Drinks');
INSERT INTO product_category(category_name) VALUES ('Spices');
INSERT INTO product_category(category_name) VALUES ('Vegetables');
INSERT INTO product_category(category_name) VALUES ('Fruits');

-- -----------------------------------------------------
-- Drinks
-- -----------------------------------------------------

INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1000', 'Simply Orange', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-07.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1001', 'Simply Lemonade', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-08.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1002', 'Fanta Orange', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-09.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1003', 'Schweppes', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-10.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1004', 'Simply Orange Gallon', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-11.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1005', 'Minute Maid Lemonade', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-12.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1006', 'Canada Dry Ginger Ale', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-13.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1007', 'Fanta Lemon', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-14.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1008', 'Pepsi', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-15.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1009', 'Solo original lemon', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-16.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1010', 'Pepsi no sugar', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-17.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1011', 'Diet Coke', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-18.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1012', 'V8 Organic Apple Juice', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-19.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1013', 'Langens Mango Nectar', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-20.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1014', 'Canada Dry Bold golden ale', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-01.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1015', 'Minute Maid Orange Juice', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-02.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1016', 'Sprite Cranberry', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-03.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1017', 'Glass Fanta Orange', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-04.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1018', 'Fanta orangade', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-05.png', 1, 100, 1.99, 1, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DRINKS-1019', 'Fanta grape juice', 'Great drink that quenches your thirst. Serves worldwide, and make happy customers.', 'assets/images/products/drinks/drink-06.png', 1, 100, 1.99, 1, NOW());

-- -----------------------------------------------------
-- Spices
-- -----------------------------------------------------

INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1000', 'Simply organic oregano', 'Behold, spices from the mother earth! Is your food bland? Don not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-01.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1001', 'Sesame seeds', 'Behold, spices from the mother earth! Is your food bland? Don not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-02.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1002', 'Rosemary', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-03.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1003', 'Ground Allspice', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-04.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1004', 'Rosemary leaves', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-05.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1005', 'Thyme leaves', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-06.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1006', 'Chili powder', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-07.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1007', 'Ground cinnamon', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-08.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1008', 'Organic Anise', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-09.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1009', 'Ground Turmeric', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-10.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1010', 'Candamom spice', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-11.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1011', 'Black Pepper', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-12.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1012', 'Organic Kalonji', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-13.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1013', 'Thyme Leaves', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-14.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1014', 'Green Cardamom', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-15.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1015', 'Ground Ginger', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-16.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1016', 'Basil Leaves', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-17.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1017', 'Whole Black Peppercorns', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-18.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1018', 'Ground Allspice', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-19.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('SPICES-1019', 'Ginger Firmly chopped', 'Behold, spices from the mother earth! Is your food bland? Do not worry, this spice can save your food from being thrown away! ', 'assets/images/products/Spices/spice-20.png', 1, 100, 0.99, 2, NOW());


-- -----------------------------------------------------
-- Fruits
-- -----------------------------------------------------

INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1000', 'Apple', 'Hi I am a Fruit ', 'assets/images/products/fruits/apple.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1001', 'Apricot', 'Hi I am a Fruit ', 'assets/images/products/fruits/apricot.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1002', 'Banana', 'Hi I am a Fruit ', 'assets/images/products/fruits/banana.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1003', 'Cherry', 'Hi I am a Fruit ', 'assets/images/products/fruits/cherry.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1004', 'Dragon Fruit', 'Hi I am a Fruit ', 'assets/images/products/fruits/dragonfruit.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1005', 'Fig', 'Hi I am a Fruit ', 'assets/images/products/fruits/fig.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1006', 'Grape Fruit', 'Hi I am a Fruit ', 'assets/images/products/fruits/grapefruit.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1007', 'Green Grape', 'Hi I am a Fruit ', 'assets/images/products/fruits/greengrape.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1008', 'Jackfruit', 'Hi I am a Fruit ', 'assets/images/products/fruits/jackfruit.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1009', 'Kiwi', 'Hi I am a Fruit ', 'assets/images/products/fruits/kiwi.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1010', 'Mango', 'Hi I am a Fruit ', 'assets/images/products/fruits/mango.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1011', 'Orange', 'Hi I am a Fruit ', 'assets/images/products/fruits/orange.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1012', 'Pear', 'Hi I am a Fruit ', 'assets/images/products/fruits/pear.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1013', 'Pineapple', 'Hi I am a Fruit ', 'assets/images/products/fruits/pineapple.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1014', 'Plum', 'Hi I am a Fruit ', 'assets/images/products/fruits/plum.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1015', 'Pomegranate', 'Hi I am a Fruit ', 'assets/images/products/fruits/pomegranate.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1016', 'Purple Grape', 'Hi I am a Fruit ', 'assets/images/products/fruits/purplegrape.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1017', 'Raspberry', 'Hi I am a Fruit ', 'assets/images/products/fruits/raspberry.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1018', 'Strawberry', 'Hi I am a Fruit ', 'assets/images/products/fruits/strawberry.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUITS-1019', 'Watermelon', 'Hi I am a Fruit', 'assets/images/products/fruits/watermelon.png', 1, 100, 0.99, 2, NOW());


-- -----------------------------------------------------
-- Vegetables
-- -----------------------------------------------------

INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1000', 'Asparagus', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/asparagus.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1001', 'Beans', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/beans.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1002', 'Beetroot', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/beetroot.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1003', 'BellPepper', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/bellpepper.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1004', 'Broccoli', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/broccoli.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1005', 'Cabbage', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/cabbage.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1006', 'Carrot', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/carrot.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1007', 'Cauliflower', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/cauliflower.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1008', 'Cucumber', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/cucumber.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1009', 'Egg Plant', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/eggplant.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1010', 'Kale', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/kale.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1011', 'Lettuce', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/lettuce.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1012', 'Onion', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/onion.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1013', 'Potato', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/potato.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1014', 'Pumpkin', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/pumpkin.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1015', 'Radish', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/radish.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1016', 'Spinach', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/spinach.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1017', 'Spring Onion', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/springonion.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1018', 'Tomato', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/tomato.png', 1, 100, 0.99, 2, NOW());
INSERT INTO product (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEGETABLES-1019', 'Celery', 'Hi I am a Vegetable ', 'assets/images/products/vegetables/celery.png', 1, 100, 0.99, 2, NOW());
